// @ts-nocheck
// Generated by tauri-specta. Do not edit; run `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Version of the running app, as declared in Cargo.toml. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	appFlagGet: (flag: AppFlag) => typedError<boolean, string>(__TAURI_INVOKE("app_flag_get", { flag })),
	appFlagSet: (flag: AppFlag) => typedError<null, string>(__TAURI_INVOKE("app_flag_set", { flag })),
	/**  The board window stored its pending edits; quitting may continue. */
	appReadyToQuit: () => __TAURI_INVOKE<void>("app_ready_to_quit"),
	/**  Quits the app the same way the tray menu does: pending work finishes first. */
	appQuit: () => __TAURI_INVOKE<void>("app_quit"),
	/**  Loads the board with all its items, back to front. */
	boardLoad: () => typedError<Board, string>(__TAURI_INVOKE("board_load")),
	/**  Stores a batch of edits atomically. On error nothing from the batch is stored. */
	boardApplyOps: (ops: BoardOp[]) => typedError<null, string>(__TAURI_INVOKE("board_apply_ops", { ops })),
	/**  Availability of every premium feature. Features not listed are free. */
	entitlementsGet: () => __TAURI_INVOKE<Entitlement[]>("entitlements_get"),
	/**
	 *  Imports image files (dropped onto the board or picked in a dialog). Each file gets its own
	 *  result, so one bad file does not stop the others.
	 */
	mediaImportPaths: (paths: string[]) => typedError<ImportResult[], string>(__TAURI_INVOKE("media_import_paths", { paths })),
	/**  Imports an image pasted from the clipboard, sent as base64. */
	mediaImportBytes: (base64: string) => typedError<ImportResult, string>(__TAURI_INVOKE("media_import_bytes", { base64 })),
	/**  The media directory and every stored image. */
	mediaList: () => typedError<MediaLibrary, string>(__TAURI_INVOKE("media_list")),
};

/* Types */
/**  Known flags. An enum, so the frontend cannot write arbitrary keys. */
export type AppFlag = 
/**  The user was told that closing the window keeps the app running in the tray. */
"trayNoticeShown";

export type Board = {
	id: string,
	/**  Back to front. */
	items: Item[],
};

/**
 *  One edit in a batch. Upsert carries the whole item, which covers add, move, resize,
 *  rotate, text edits and reordering with a single, idempotent operation.
 */
export type BoardOp = { op: "upsert"; item: Item } | { op: "delete"; id: string };

export type Entitlement = {
	feature: Feature,
	enabled: boolean,
};

/**  Features unlocked by an Almost-there.eu gift. Everything else is free. */
export type Feature = "premiumFrames" | "wallpaper" | "scheduledPopup";

/**  Why one file could not be imported; the UI shows a localized message per kind. */
export type ImportErrorKind = "tooLarge" | "unsupported" | "unreadable";

export type ImportResult = { status: "ok"; media: Media } | { status: "error"; kind: ImportErrorKind; 
/**  File name (without directories) for the message. */
name: string };

export type Item = {
	/**  Generated by the frontend (UUID), so edits can be applied optimistically. */
	id: string,
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
	/**  Degrees, clockwise. */
	rotation: number | null,
	/**  Stacking order; higher is in front. */
	z: number,
	content: ItemContent,
	style?: ItemStyle,
};

/**  What an item shows. The tag doubles as the item kind stored in the database. */
export type ItemContent = { kind: "image"; mediaId: string } | { kind: "quote"; text: string; author: string | null } | { kind: "text"; text: string; variant: TextVariant };

/**  Per-item visual overrides. Empty until frame styles arrive in phase 2. */
export type ItemStyle = Record<string, never>;

export type Media = {
	id: string,
	fileName: string,
	thumbName: string,
	width: number,
	height: number,
	/**  Size of the stored full-size file. */
	bytes: number,
};

export type MediaLibrary = {
	/**  Absolute media directory; the frontend turns `dir/fileName` into an asset URL. */
	dir: string,
	items: Media[],
};

export type TextVariant = "heading" | "note";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

