// @ts-nocheck
// Generated by tauri-specta. Do not edit; run `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Version of the running app, as declared in Cargo.toml. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
};

