// @ts-nocheck
// Generated by tauri-specta. Do not edit; run `pnpm bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Version of the running app, as declared in Cargo.toml. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**  Loads the board with all its items, back to front. */
	boardLoad: () => typedError<Board, string>(__TAURI_INVOKE("board_load")),
	/**  Stores a batch of edits atomically. On error nothing from the batch is stored. */
	boardApplyOps: (ops: BoardOp[]) => typedError<null, string>(__TAURI_INVOKE("board_apply_ops", { ops })),
};

/* Types */
export type Board = {
	id: string,
	/**  Back to front. */
	items: Item[],
};

/**
 *  One edit in a batch. Upsert carries the whole item, which covers add, move, resize,
 *  rotate, text edits and reordering with a single, idempotent operation.
 */
export type BoardOp = { op: "upsert"; item: Item } | { op: "delete"; id: string };

export type Item = {
	/**  Generated by the frontend (UUID), so edits can be applied optimistically. */
	id: string,
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
	/**  Degrees, clockwise. */
	rotation: number | null,
	/**  Stacking order; higher is in front. */
	z: number,
	content: ItemContent,
	style?: ItemStyle,
};

/**  What an item shows. The tag doubles as the item kind stored in the database. */
export type ItemContent = { kind: "image"; mediaId: string } | { kind: "quote"; text: string; author: string | null } | { kind: "text"; text: string; variant: TextVariant };

/**  Per-item visual overrides. Empty until frame styles arrive in phase 2. */
export type ItemStyle = Record<string, never>;

export type TextVariant = "heading" | "note";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

