//! Tauri commands: a thin IPC layer that validates input and delegates to `domain`.
//!
//! Every command is registered in [`builder`], which also generates the TypeScript bindings
//! in `src/lib/bindings.ts` (run `pnpm bindings`).

mod app;
mod board;
mod entitlements;
mod media;

use std::time::{SystemTime, UNIX_EPOCH};

use tauri_specta::{collect_commands, Builder};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        app::app_version,
        board::board_load,
        board::board_apply_ops,
        entitlements::entitlements_get,
        media::media_import_paths,
        media::media_import_bytes,
        media::media_list,
    ])
}

/// Wall-clock time in milliseconds since the Unix epoch, for created/updated timestamps.
fn now_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| i64::try_from(d.as_millis()).unwrap_or(i64::MAX))
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    /// Regenerates the frontend bindings. CI fails when the committed file is stale.
    #[test]
    fn export_bindings() {
        super::builder()
            .export(
                Typescript::default().header("// @ts-nocheck\n// Generated by tauri-specta. Do not edit; run `pnpm bindings`.\n"),
                "../src/lib/bindings.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
