//! Tauri commands: a thin IPC layer that validates input and delegates to `domain`.
//!
//! Every command is registered in [`builder`], which also generates the TypeScript bindings
//! in `src/lib/bindings.ts` (run `pnpm bindings`).

mod app;
mod board;

use tauri_specta::{collect_commands, Builder};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        app::app_version,
        board::board_load,
        board::board_apply_ops,
    ])
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    /// Regenerates the frontend bindings. CI fails when the committed file is stale.
    #[test]
    fn export_bindings() {
        super::builder()
            .export(
                Typescript::default().header("// @ts-nocheck\n// Generated by tauri-specta. Do not edit; run `pnpm bindings`.\n"),
                "../src/lib/bindings.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
