//! The vision board: items on a logical 1920×1080 canvas and the batched edits applied to them.

use rusqlite::{params, Connection, OptionalExtension, Transaction};
use serde::{Deserialize, Serialize};
use specta::Type;

use super::settings::FrameStyle;

/// Logical canvas size. Item geometry is stored in these units and scaled by the renderer.
pub const CANVAS_WIDTH: f64 = 1920.0;
pub const CANVAS_HEIGHT: f64 = 1080.0;

const MAX_ID_LEN: usize = 64;
const MAX_TEXT_LEN: usize = 2000;
const MAX_AUTHOR_LEN: usize = 200;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum TextVariant {
    Heading,
    Note,
}

/// What an item shows. The tag doubles as the item kind stored in the database.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ItemContent {
    Image {
        #[serde(rename = "mediaId")]
        media_id: String,
        /// Buttons on the image (at most 5); older boards have none.
        #[serde(default)]
        hotspots: Vec<Hotspot>,
    },
    Quote {
        text: String,
        author: Option<String>,
    },
    Text {
        text: String,
        variant: TextVariant,
    },
}

/// A button on an image that leads further: to a web page or to a small window with more
/// photos and text.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Hotspot {
    pub id: String,
    /// Position as a fraction of the image (0–1), so it moves and scales with it.
    pub x: f64,
    pub y: f64,
    pub label: String,
    pub action: HotspotAction,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum HotspotAction {
    /// Opens in the default browser; http and https only.
    Link { url: String },
    Detail {
        title: String,
        text: String,
        /// Further photos (stored media), shown as a gallery.
        media: Vec<String>,
    },
}

pub const MAX_HOTSPOTS: usize = 5;
pub const MAX_DETAIL_MEDIA: usize = 20;
const MAX_LABEL_LEN: usize = 40;
const MAX_TITLE_LEN: usize = 80;
const MAX_URL_LEN: usize = 2000;

/// Whether `url` is an absolute http(s) address with a host; nothing else may be opened.
pub fn is_web_link(url: &str) -> bool {
    url.len() <= MAX_URL_LEN
        && url::Url::parse(url)
            .is_ok_and(|u| matches!(u.scheme(), "http" | "https") && u.host_str().is_some())
}

impl ItemContent {
    /// Every stored image the item shows: the image itself and its hotspots' galleries.
    pub fn media_ids(&self) -> Vec<&str> {
        match self {
            Self::Image {
                media_id, hotspots, ..
            } => std::iter::once(media_id.as_str())
                .chain(hotspots.iter().flat_map(|h| match &h.action {
                    HotspotAction::Detail { media, .. } => {
                        media.iter().map(String::as_str).collect()
                    }
                    HotspotAction::Link { .. } => Vec::new(),
                }))
                .collect(),
            _ => Vec::new(),
        }
    }

    fn kind(&self) -> &'static str {
        match self {
            Self::Image { .. } => "image",
            Self::Quote { .. } => "quote",
            Self::Text { .. } => "text",
        }
    }
}

/// Per-item visual overrides.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct ItemStyle {
    /// Frame of an image; none follows the board default (settings). A frame this version does
    /// not know makes the stored style unreadable, which `load` treats as the default style.
    #[serde(default)]
    pub frame: Option<FrameStyle>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Item {
    /// Generated by the frontend (UUID), so edits can be applied optimistically.
    pub id: String,
    pub x: f64,
    pub y: f64,
    pub w: f64,
    pub h: f64,
    /// Degrees, clockwise.
    pub rotation: f64,
    /// Stacking order; higher is in front.
    pub z: i32,
    pub content: ItemContent,
    #[serde(default)]
    pub style: ItemStyle,
}

/// One edit in a batch. Upsert carries the whole item, which covers add, move, resize,
/// rotate, text edits and reordering with a single, idempotent operation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "op", rename_all = "camelCase")]
pub enum BoardOp {
    Upsert { item: Item },
    Delete { id: String },
}

#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Board {
    pub id: String,
    /// Back to front.
    pub items: Vec<Item>,
}

#[derive(Debug, thiserror::Error)]
pub enum BoardError {
    #[error("board {0} does not exist")]
    UnknownBoard(String),
    #[error("invalid item {id}: {reason}")]
    InvalidItem { id: String, reason: &'static str },
    #[error("image item {id} refers to unknown media {media_id}")]
    UnknownMedia { id: String, media_id: String },
    #[error(transparent)]
    Sqlite(#[from] rusqlite::Error),
    #[error("stored item {id} is corrupt: {source}")]
    Corrupt {
        id: String,
        source: serde_json::Error,
    },
}

pub fn load(conn: &Connection, board_id: &str) -> Result<Board, BoardError> {
    ensure_board(conn, board_id)?;
    let mut stmt = conn.prepare(
        "SELECT id, x, y, w, h, rotation, z, payload, style
         FROM items WHERE board_id = ?1 ORDER BY z, created_at",
    )?;
    let rows = stmt.query_map([board_id], |r| {
        Ok((
            r.get::<_, String>(0)?,
            [r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?, r.get(5)?],
            r.get::<_, i32>(6)?,
            r.get::<_, String>(7)?,
            r.get::<_, String>(8)?,
        ))
    })?;

    let mut items = Vec::new();
    for row in rows {
        let (id, [x, y, w, h, rotation], z, payload, style) = row?;
        let content = serde_json::from_str(&payload).map_err(|source| BoardError::Corrupt {
            id: id.clone(),
            source,
        })?;
        // Style is cosmetic: an unreadable style falls back to the default instead of
        // hiding the item.
        let style = serde_json::from_str(&style).unwrap_or_default();
        items.push(Item {
            id,
            x,
            y,
            w,
            h,
            rotation,
            z,
            content,
            style,
        });
    }
    Ok(Board {
        id: board_id.to_owned(),
        items,
    })
}

/// Applies a batch of edits atomically: either every op is stored, or none is.
pub fn apply_ops(
    conn: &mut Connection,
    board_id: &str,
    ops: &[BoardOp],
    now_ms: i64,
) -> Result<(), BoardError> {
    let tx = conn.transaction()?;
    ensure_board(&tx, board_id)?;
    for op in ops {
        match op {
            BoardOp::Upsert { item } => upsert(&tx, board_id, item, now_ms)?,
            BoardOp::Delete { id } => {
                tx.execute(
                    "DELETE FROM items WHERE id = ?1 AND board_id = ?2",
                    params![id, board_id],
                )?;
            }
        }
    }
    tx.execute(
        "UPDATE boards SET updated_at = ?1 WHERE id = ?2",
        params![now_ms, board_id],
    )?;
    tx.commit()?;
    Ok(())
}

fn ensure_board(conn: &Connection, board_id: &str) -> Result<(), BoardError> {
    conn.query_row("SELECT 1 FROM boards WHERE id = ?1", [board_id], |_| Ok(()))
        .optional()?
        .ok_or_else(|| BoardError::UnknownBoard(board_id.to_owned()))
}

fn upsert(tx: &Transaction, board_id: &str, item: &Item, now_ms: i64) -> Result<(), BoardError> {
    validate(item)?;
    for media_id in item.content.media_ids() {
        let exists = tx
            .query_row("SELECT 1 FROM media WHERE id = ?1", [media_id], |_| Ok(()))
            .optional()?
            .is_some();
        if !exists {
            return Err(BoardError::UnknownMedia {
                id: item.id.clone(),
                media_id: media_id.to_owned(),
            });
        }
    }

    let payload = serde_json::to_string(&item.content).expect("item content serializes");
    let style = serde_json::to_string(&item.style).expect("item style serializes");
    // An existing id on another board is not overwritten: the WHERE clause on the update
    // leaves it untouched and the change count below reports the conflict.
    let changed = tx.execute(
        "INSERT INTO items (id, board_id, kind, x, y, w, h, rotation, z, payload, style, created_at, updated_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?12)
         ON CONFLICT (id) DO UPDATE SET
            kind = excluded.kind, x = excluded.x, y = excluded.y, w = excluded.w, h = excluded.h,
            rotation = excluded.rotation, z = excluded.z, payload = excluded.payload,
            style = excluded.style, updated_at = excluded.updated_at
         WHERE items.board_id = excluded.board_id",
        params![
            item.id,
            board_id,
            item.content.kind(),
            item.x,
            item.y,
            item.w,
            item.h,
            item.rotation,
            item.z,
            payload,
            style,
            now_ms
        ],
    )?;
    if changed == 0 {
        return Err(invalid(item, "id belongs to another board"));
    }
    Ok(())
}

fn invalid(item: &Item, reason: &'static str) -> BoardError {
    BoardError::InvalidItem {
        id: item.id.clone(),
        reason,
    }
}

/// Rejects data the UI should never produce, so a frontend bug cannot corrupt the board.
/// Positioning rules (e.g. staying partly on the canvas) are enforced by the UI.
fn validate(item: &Item) -> Result<(), BoardError> {
    if item.id.is_empty() || item.id.len() > MAX_ID_LEN {
        return Err(invalid(item, "id must be 1–64 characters"));
    }
    let geometry = [item.x, item.y, item.w, item.h, item.rotation];
    if geometry.iter().any(|v| !v.is_finite()) {
        return Err(invalid(item, "geometry must be finite"));
    }
    if item.w <= 0.0 || item.h <= 0.0 {
        return Err(invalid(item, "size must be positive"));
    }
    // Generous bounds: far outside the canvas is a bug, not a user action.
    let limit = 4.0 * CANVAS_WIDTH.max(CANVAS_HEIGHT);
    if geometry[..4].iter().any(|v| v.abs() > limit) {
        return Err(invalid(item, "geometry is out of range"));
    }
    if item.rotation.abs() > 15.0 {
        return Err(invalid(item, "rotation must be within ±15°"));
    }
    match &item.content {
        ItemContent::Image { media_id, .. } if media_id.is_empty() => {
            Err(invalid(item, "image needs media"))
        }
        ItemContent::Image { hotspots, .. } => validate_hotspots(item, hotspots),
        ItemContent::Quote { text, author } => {
            check_text(item, text)?;
            match author {
                Some(a) if a.chars().count() > MAX_AUTHOR_LEN => {
                    Err(invalid(item, "author is too long"))
                }
                _ => Ok(()),
            }
        }
        ItemContent::Text { text, .. } => check_text(item, text),
    }
}

fn validate_hotspots(item: &Item, hotspots: &[Hotspot]) -> Result<(), BoardError> {
    if hotspots.len() > MAX_HOTSPOTS {
        return Err(invalid(item, "an image has at most 5 hotspots"));
    }
    let mut ids = std::collections::HashSet::new();
    for hotspot in hotspots {
        if hotspot.id.is_empty() || hotspot.id.len() > MAX_ID_LEN || !ids.insert(&hotspot.id) {
            return Err(invalid(item, "hotspot ids must be unique, 1–64 characters"));
        }
        if !(0.0..=1.0).contains(&hotspot.x) || !(0.0..=1.0).contains(&hotspot.y) {
            return Err(invalid(item, "hotspot must lie on the image"));
        }
        let label = hotspot.label.trim();
        if label.is_empty() || label.chars().count() > MAX_LABEL_LEN {
            return Err(invalid(item, "hotspot label must be 1–40 characters"));
        }
        match &hotspot.action {
            HotspotAction::Link { url } if !is_web_link(url) => {
                return Err(invalid(
                    item,
                    "hotspot link must be an http or https address",
                ));
            }
            HotspotAction::Detail { title, text, media } => {
                if title.trim().is_empty() || title.chars().count() > MAX_TITLE_LEN {
                    return Err(invalid(item, "detail title must be 1–80 characters"));
                }
                if text.chars().count() > MAX_TEXT_LEN {
                    return Err(invalid(item, "detail text is too long"));
                }
                if media.len() > MAX_DETAIL_MEDIA || media.iter().any(String::is_empty) {
                    return Err(invalid(item, "a detail has at most 20 photos"));
                }
            }
            HotspotAction::Link { .. } => {}
        }
    }
    Ok(())
}

fn check_text(item: &Item, text: &str) -> Result<(), BoardError> {
    if text.trim().is_empty() {
        return Err(invalid(item, "text must not be empty"));
    }
    if text.chars().count() > MAX_TEXT_LEN {
        return Err(invalid(item, "text is too long"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::db::{open_in_memory, DEFAULT_BOARD_ID};

    fn quote(id: &str, z: i32) -> Item {
        Item {
            id: id.into(),
            x: 100.0,
            y: 200.0,
            w: 400.0,
            h: 160.0,
            rotation: 0.0,
            z,
            content: ItemContent::Quote {
                text: "Cíl bez plánu je jen přání.".into(),
                author: Some("Antoine de Saint-Exupéry".into()),
            },
            style: ItemStyle::default(),
        }
    }

    fn upsert(item: Item) -> BoardOp {
        BoardOp::Upsert { item }
    }

    fn add_media(conn: &Connection, id: &str) {
        conn.execute(
            "INSERT INTO media (id, file_name, thumb_name, width, height, bytes, created_at)
             VALUES (?1, 'a.webp', 'a_t.webp', 10, 10, 100, 0)",
            [id],
        )
        .expect("insert media");
    }

    #[test]
    fn new_board_is_empty() {
        let conn = open_in_memory();
        let board = load(&conn, DEFAULT_BOARD_ID).expect("load");
        assert_eq!(board.id, DEFAULT_BOARD_ID);
        assert!(board.items.is_empty());
    }

    #[test]
    fn stored_items_load_back_in_stacking_order() {
        let mut conn = open_in_memory();
        add_media(&conn, "m1");
        let image = Item {
            content: ItemContent::Image {
                media_id: "m1".into(),
                hotspots: vec![],
            },
            ..quote("b", 1)
        };
        let text = Item {
            content: ItemContent::Text {
                text: "2027".into(),
                variant: TextVariant::Heading,
            },
            ..quote("c", 0)
        };
        let ops = [
            upsert(quote("a", 2)),
            upsert(image.clone()),
            upsert(text.clone()),
        ];
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &ops, 1).expect("apply");

        let board = load(&conn, DEFAULT_BOARD_ID).expect("load");
        assert_eq!(board.items, vec![text, image, quote("a", 2)]);
    }

    #[test]
    fn stores_the_frame_of_an_item() {
        let mut conn = open_in_memory();
        add_media(&conn, "m1");
        let framed = Item {
            content: ItemContent::Image {
                media_id: "m1".into(),
                hotspots: vec![],
            },
            style: ItemStyle {
                frame: Some(FrameStyle::Polaroid),
            },
            ..quote("a", 0)
        };
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(framed.clone())], 1).expect("apply");
        assert_eq!(
            load(&conn, DEFAULT_BOARD_ID).expect("load").items,
            vec![framed]
        );
    }

    #[test]
    fn unknown_frame_reads_as_board_default() {
        let mut conn = open_in_memory();
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("a", 0))], 1).expect("add");
        conn.execute("UPDATE items SET style = '{\"frame\":\"neon\"}'", [])
            .expect("style from a newer version");
        let items = load(&conn, DEFAULT_BOARD_ID).expect("load").items;
        assert_eq!(items[0].style.frame, None);
    }

    fn hotspot(id: &str, action: HotspotAction) -> Hotspot {
        Hotspot {
            id: id.into(),
            x: 0.3,
            y: 0.6,
            label: "Ubytování".into(),
            action,
        }
    }

    fn link(url: &str) -> HotspotAction {
        HotspotAction::Link { url: url.into() }
    }

    fn image_with(hotspots: Vec<Hotspot>) -> Item {
        Item {
            content: ItemContent::Image {
                media_id: "m1".into(),
                hotspots,
            },
            ..quote("img", 0)
        }
    }

    #[test]
    fn stores_hotspots_with_the_image() {
        let mut conn = open_in_memory();
        add_media(&conn, "m1");
        add_media(&conn, "m2");
        let item = image_with(vec![
            hotspot("h1", link("https://example.com/ubytovani")),
            hotspot(
                "h2",
                HotspotAction::Detail {
                    title: "Dům snů".into(),
                    text: "Terasa s výhledem".into(),
                    media: vec!["m2".into()],
                },
            ),
        ]);
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(item.clone())], 1).expect("apply");
        assert_eq!(
            load(&conn, DEFAULT_BOARD_ID).expect("load").items,
            vec![item]
        );
    }

    #[test]
    fn an_image_from_before_hotspots_loads_without_them() {
        let content: ItemContent =
            serde_json::from_str(r#"{"kind":"image","mediaId":"m1"}"#).expect("old payload");
        assert_eq!(
            content,
            ItemContent::Image {
                media_id: "m1".into(),
                hotspots: vec![]
            }
        );
    }

    #[test]
    fn only_web_links_are_accepted() {
        assert!(is_web_link("https://example.com"));
        assert!(is_web_link("http://example.com/a?b=c"));
        for bad in [
            "file:///C:/Windows",
            "javascript:alert(1)",
            "ftp://example.com",
            "example.com",
            "https://",
            "",
        ] {
            assert!(!is_web_link(bad), "{bad}");
        }

        let mut conn = open_in_memory();
        add_media(&conn, "m1");
        let item = image_with(vec![hotspot("h1", link("javascript:alert(1)"))]);
        assert!(apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(item)], 1).is_err());
    }

    #[test]
    fn rejects_too_many_or_misplaced_hotspots() {
        let mut conn = open_in_memory();
        add_media(&conn, "m1");
        let six: Vec<_> = (0..6)
            .map(|i| hotspot(&format!("h{i}"), link("https://example.com")))
            .collect();
        assert!(apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(image_with(six))], 1).is_err());

        let mut outside = hotspot("h1", link("https://example.com"));
        outside.x = 1.2;
        assert!(apply_ops(
            &mut conn,
            DEFAULT_BOARD_ID,
            &[upsert(image_with(vec![outside]))],
            1
        )
        .is_err());

        let twins = vec![
            hotspot("h1", link("https://a.example")),
            hotspot("h1", link("https://b.example")),
        ];
        assert!(apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(image_with(twins))], 1).is_err());
    }

    #[test]
    fn a_detail_must_use_stored_photos() {
        let mut conn = open_in_memory();
        add_media(&conn, "m1");
        let item = image_with(vec![hotspot(
            "h1",
            HotspotAction::Detail {
                title: "Dům".into(),
                text: String::new(),
                media: vec!["missing".into()],
            },
        )]);
        assert!(matches!(
            apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(item)], 1),
            Err(BoardError::UnknownMedia { .. })
        ));
    }

    #[test]
    fn upsert_updates_an_existing_item() {
        let mut conn = open_in_memory();
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("a", 0))], 1).expect("add");
        let moved = Item {
            x: 900.0,
            rotation: -8.0,
            ..quote("a", 3)
        };
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(moved.clone())], 2).expect("move");
        assert_eq!(
            load(&conn, DEFAULT_BOARD_ID).expect("load").items,
            vec![moved]
        );
    }

    #[test]
    fn delete_removes_the_item() {
        let mut conn = open_in_memory();
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("a", 0))], 1).expect("add");
        apply_ops(
            &mut conn,
            DEFAULT_BOARD_ID,
            &[BoardOp::Delete { id: "a".into() }],
            2,
        )
        .expect("delete");
        assert!(load(&conn, DEFAULT_BOARD_ID)
            .expect("load")
            .items
            .is_empty());
    }

    #[test]
    fn a_failing_op_rolls_back_the_whole_batch() {
        let mut conn = open_in_memory();
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("keep", 0))], 1).expect("seed");

        let empty_quote = Item {
            content: ItemContent::Quote {
                text: "   ".into(),
                author: None,
            },
            ..quote("bad", 2)
        };
        let ops = [
            upsert(quote("new", 1)),
            BoardOp::Delete { id: "keep".into() },
            upsert(empty_quote),
        ];
        let err = apply_ops(&mut conn, DEFAULT_BOARD_ID, &ops, 2).expect_err("batch fails");
        assert!(matches!(err, BoardError::InvalidItem { .. }));

        let ids: Vec<_> = load(&conn, DEFAULT_BOARD_ID)
            .expect("load")
            .items
            .into_iter()
            .map(|i| i.id)
            .collect();
        assert_eq!(ids, ["keep"]);
    }

    #[test]
    fn rejects_image_with_unknown_media() {
        let mut conn = open_in_memory();
        let image = Item {
            content: ItemContent::Image {
                media_id: "missing".into(),
                hotspots: vec![],
            },
            ..quote("i", 0)
        };
        let err = apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(image)], 1).expect_err("fails");
        assert!(matches!(err, BoardError::UnknownMedia { .. }));
    }

    #[test]
    fn rejects_invalid_geometry_and_text() {
        let cases = [
            Item {
                w: 0.0,
                ..quote("a", 0)
            },
            Item {
                x: f64::NAN,
                ..quote("a", 0)
            },
            Item {
                y: 1e9,
                ..quote("a", 0)
            },
            Item {
                rotation: 30.0,
                ..quote("a", 0)
            },
            Item {
                id: String::new(),
                ..quote("a", 0)
            },
            Item {
                content: ItemContent::Text {
                    text: "x".repeat(MAX_TEXT_LEN + 1),
                    variant: TextVariant::Note,
                },
                ..quote("a", 0)
            },
        ];
        for item in cases {
            let mut conn = open_in_memory();
            let result = apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(item.clone())], 1);
            assert!(
                matches!(result, Err(BoardError::InvalidItem { .. })),
                "{item:?} should be rejected"
            );
        }
    }

    #[test]
    fn unknown_board_is_an_error() {
        let mut conn = open_in_memory();
        assert!(matches!(
            load(&conn, "nope"),
            Err(BoardError::UnknownBoard(_))
        ));
        assert!(matches!(
            apply_ops(&mut conn, "nope", &[upsert(quote("a", 0))], 1),
            Err(BoardError::UnknownBoard(_))
        ));
    }

    #[test]
    fn item_ids_cannot_be_taken_over_by_another_board() {
        let mut conn = open_in_memory();
        conn.execute(
            "INSERT INTO boards (id, name, created_at, updated_at) VALUES ('other', '', 0, 0)",
            [],
        )
        .expect("second board");
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("a", 0))], 1).expect("add");
        let result = apply_ops(&mut conn, "other", &[upsert(quote("a", 5))], 2);
        assert!(matches!(result, Err(BoardError::InvalidItem { .. })));
        assert_eq!(load(&conn, DEFAULT_BOARD_ID).expect("load").items[0].z, 0);
    }

    #[test]
    fn serializes_items_in_the_shape_the_frontend_expects() {
        let json = serde_json::to_value(quote("a", 0)).expect("serialize");
        assert_eq!(json["content"]["kind"], "quote");
        assert_eq!(json["content"]["author"], "Antoine de Saint-Exupéry");
        let op: BoardOp = serde_json::from_value(serde_json::json!({
            "op": "upsert",
            "item": {
                "id": "x", "x": 1.0, "y": 2.0, "w": 3.0, "h": 4.0, "rotation": 0.0, "z": 0,
                "content": { "kind": "image", "mediaId": "m1" }
            }
        }))
        .expect("deserialize");
        assert!(
            matches!(op, BoardOp::Upsert { item } if item.content == ItemContent::Image { media_id: "m1".into(), hotspots: vec![] })
        );
    }
}
