//! The vision board: items on a logical 1920×1080 canvas and the batched edits applied to them.

use rusqlite::{params, Connection, OptionalExtension, Transaction};
use serde::{Deserialize, Serialize};
use specta::Type;

/// Logical canvas size. Item geometry is stored in these units and scaled by the renderer.
pub const CANVAS_WIDTH: f64 = 1920.0;
pub const CANVAS_HEIGHT: f64 = 1080.0;

const MAX_ID_LEN: usize = 64;
const MAX_TEXT_LEN: usize = 2000;
const MAX_AUTHOR_LEN: usize = 200;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum TextVariant {
    Heading,
    Note,
}

/// What an item shows. The tag doubles as the item kind stored in the database.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ItemContent {
    Image {
        #[serde(rename = "mediaId")]
        media_id: String,
    },
    Quote {
        text: String,
        author: Option<String>,
    },
    Text {
        text: String,
        variant: TextVariant,
    },
}

impl ItemContent {
    fn kind(&self) -> &'static str {
        match self {
            Self::Image { .. } => "image",
            Self::Quote { .. } => "quote",
            Self::Text { .. } => "text",
        }
    }
}

/// Per-item visual overrides. Empty until frame styles arrive in phase 2.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct ItemStyle {}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Item {
    /// Generated by the frontend (UUID), so edits can be applied optimistically.
    pub id: String,
    pub x: f64,
    pub y: f64,
    pub w: f64,
    pub h: f64,
    /// Degrees, clockwise.
    pub rotation: f64,
    /// Stacking order; higher is in front.
    pub z: i32,
    pub content: ItemContent,
    #[serde(default)]
    pub style: ItemStyle,
}

/// One edit in a batch. Upsert carries the whole item, which covers add, move, resize,
/// rotate, text edits and reordering with a single, idempotent operation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "op", rename_all = "camelCase")]
pub enum BoardOp {
    Upsert { item: Item },
    Delete { id: String },
}

#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Board {
    pub id: String,
    /// Back to front.
    pub items: Vec<Item>,
}

#[derive(Debug, thiserror::Error)]
pub enum BoardError {
    #[error("board {0} does not exist")]
    UnknownBoard(String),
    #[error("invalid item {id}: {reason}")]
    InvalidItem { id: String, reason: &'static str },
    #[error("image item {id} refers to unknown media {media_id}")]
    UnknownMedia { id: String, media_id: String },
    #[error(transparent)]
    Sqlite(#[from] rusqlite::Error),
    #[error("stored item {id} is corrupt: {source}")]
    Corrupt {
        id: String,
        source: serde_json::Error,
    },
}

pub fn load(conn: &Connection, board_id: &str) -> Result<Board, BoardError> {
    ensure_board(conn, board_id)?;
    let mut stmt = conn.prepare(
        "SELECT id, x, y, w, h, rotation, z, payload, style
         FROM items WHERE board_id = ?1 ORDER BY z, created_at",
    )?;
    let rows = stmt.query_map([board_id], |r| {
        Ok((
            r.get::<_, String>(0)?,
            [r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?, r.get(5)?],
            r.get::<_, i32>(6)?,
            r.get::<_, String>(7)?,
            r.get::<_, String>(8)?,
        ))
    })?;

    let mut items = Vec::new();
    for row in rows {
        let (id, [x, y, w, h, rotation], z, payload, style) = row?;
        let content = serde_json::from_str(&payload).map_err(|source| BoardError::Corrupt {
            id: id.clone(),
            source,
        })?;
        // Style is cosmetic: an unreadable style falls back to the default instead of
        // hiding the item.
        let style = serde_json::from_str(&style).unwrap_or_default();
        items.push(Item {
            id,
            x,
            y,
            w,
            h,
            rotation,
            z,
            content,
            style,
        });
    }
    Ok(Board {
        id: board_id.to_owned(),
        items,
    })
}

/// Applies a batch of edits atomically: either every op is stored, or none is.
pub fn apply_ops(
    conn: &mut Connection,
    board_id: &str,
    ops: &[BoardOp],
    now_ms: i64,
) -> Result<(), BoardError> {
    let tx = conn.transaction()?;
    ensure_board(&tx, board_id)?;
    for op in ops {
        match op {
            BoardOp::Upsert { item } => upsert(&tx, board_id, item, now_ms)?,
            BoardOp::Delete { id } => {
                tx.execute(
                    "DELETE FROM items WHERE id = ?1 AND board_id = ?2",
                    params![id, board_id],
                )?;
            }
        }
    }
    tx.execute(
        "UPDATE boards SET updated_at = ?1 WHERE id = ?2",
        params![now_ms, board_id],
    )?;
    tx.commit()?;
    Ok(())
}

fn ensure_board(conn: &Connection, board_id: &str) -> Result<(), BoardError> {
    conn.query_row("SELECT 1 FROM boards WHERE id = ?1", [board_id], |_| Ok(()))
        .optional()?
        .ok_or_else(|| BoardError::UnknownBoard(board_id.to_owned()))
}

fn upsert(tx: &Transaction, board_id: &str, item: &Item, now_ms: i64) -> Result<(), BoardError> {
    validate(item)?;
    if let ItemContent::Image { media_id } = &item.content {
        let exists = tx
            .query_row("SELECT 1 FROM media WHERE id = ?1", [media_id], |_| Ok(()))
            .optional()?
            .is_some();
        if !exists {
            return Err(BoardError::UnknownMedia {
                id: item.id.clone(),
                media_id: media_id.clone(),
            });
        }
    }

    let payload = serde_json::to_string(&item.content).expect("item content serializes");
    let style = serde_json::to_string(&item.style).expect("item style serializes");
    // An existing id on another board is not overwritten: the WHERE clause on the update
    // leaves it untouched and the change count below reports the conflict.
    let changed = tx.execute(
        "INSERT INTO items (id, board_id, kind, x, y, w, h, rotation, z, payload, style, created_at, updated_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?12)
         ON CONFLICT (id) DO UPDATE SET
            kind = excluded.kind, x = excluded.x, y = excluded.y, w = excluded.w, h = excluded.h,
            rotation = excluded.rotation, z = excluded.z, payload = excluded.payload,
            style = excluded.style, updated_at = excluded.updated_at
         WHERE items.board_id = excluded.board_id",
        params![
            item.id,
            board_id,
            item.content.kind(),
            item.x,
            item.y,
            item.w,
            item.h,
            item.rotation,
            item.z,
            payload,
            style,
            now_ms
        ],
    )?;
    if changed == 0 {
        return Err(invalid(item, "id belongs to another board"));
    }
    Ok(())
}

fn invalid(item: &Item, reason: &'static str) -> BoardError {
    BoardError::InvalidItem {
        id: item.id.clone(),
        reason,
    }
}

/// Rejects data the UI should never produce, so a frontend bug cannot corrupt the board.
/// Positioning rules (e.g. staying partly on the canvas) are enforced by the UI.
fn validate(item: &Item) -> Result<(), BoardError> {
    if item.id.is_empty() || item.id.len() > MAX_ID_LEN {
        return Err(invalid(item, "id must be 1–64 characters"));
    }
    let geometry = [item.x, item.y, item.w, item.h, item.rotation];
    if geometry.iter().any(|v| !v.is_finite()) {
        return Err(invalid(item, "geometry must be finite"));
    }
    if item.w <= 0.0 || item.h <= 0.0 {
        return Err(invalid(item, "size must be positive"));
    }
    // Generous bounds: far outside the canvas is a bug, not a user action.
    let limit = 4.0 * CANVAS_WIDTH.max(CANVAS_HEIGHT);
    if geometry[..4].iter().any(|v| v.abs() > limit) {
        return Err(invalid(item, "geometry is out of range"));
    }
    if item.rotation.abs() > 15.0 {
        return Err(invalid(item, "rotation must be within ±15°"));
    }
    match &item.content {
        ItemContent::Image { media_id } if media_id.is_empty() => {
            Err(invalid(item, "image needs media"))
        }
        ItemContent::Quote { text, author } => {
            check_text(item, text)?;
            match author {
                Some(a) if a.chars().count() > MAX_AUTHOR_LEN => {
                    Err(invalid(item, "author is too long"))
                }
                _ => Ok(()),
            }
        }
        ItemContent::Text { text, .. } => check_text(item, text),
        ItemContent::Image { .. } => Ok(()),
    }
}

fn check_text(item: &Item, text: &str) -> Result<(), BoardError> {
    if text.trim().is_empty() {
        return Err(invalid(item, "text must not be empty"));
    }
    if text.chars().count() > MAX_TEXT_LEN {
        return Err(invalid(item, "text is too long"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::db::{open_in_memory, DEFAULT_BOARD_ID};

    fn quote(id: &str, z: i32) -> Item {
        Item {
            id: id.into(),
            x: 100.0,
            y: 200.0,
            w: 400.0,
            h: 160.0,
            rotation: 0.0,
            z,
            content: ItemContent::Quote {
                text: "Cíl bez plánu je jen přání.".into(),
                author: Some("Antoine de Saint-Exupéry".into()),
            },
            style: ItemStyle::default(),
        }
    }

    fn upsert(item: Item) -> BoardOp {
        BoardOp::Upsert { item }
    }

    fn add_media(conn: &Connection, id: &str) {
        conn.execute(
            "INSERT INTO media (id, file_name, thumb_name, width, height, bytes, created_at)
             VALUES (?1, 'a.webp', 'a_t.webp', 10, 10, 100, 0)",
            [id],
        )
        .expect("insert media");
    }

    #[test]
    fn new_board_is_empty() {
        let conn = open_in_memory();
        let board = load(&conn, DEFAULT_BOARD_ID).expect("load");
        assert_eq!(board.id, DEFAULT_BOARD_ID);
        assert!(board.items.is_empty());
    }

    #[test]
    fn stored_items_load_back_in_stacking_order() {
        let mut conn = open_in_memory();
        add_media(&conn, "m1");
        let image = Item {
            content: ItemContent::Image {
                media_id: "m1".into(),
            },
            ..quote("b", 1)
        };
        let text = Item {
            content: ItemContent::Text {
                text: "2027".into(),
                variant: TextVariant::Heading,
            },
            ..quote("c", 0)
        };
        let ops = [
            upsert(quote("a", 2)),
            upsert(image.clone()),
            upsert(text.clone()),
        ];
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &ops, 1).expect("apply");

        let board = load(&conn, DEFAULT_BOARD_ID).expect("load");
        assert_eq!(board.items, vec![text, image, quote("a", 2)]);
    }

    #[test]
    fn upsert_updates_an_existing_item() {
        let mut conn = open_in_memory();
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("a", 0))], 1).expect("add");
        let moved = Item {
            x: 900.0,
            rotation: -8.0,
            ..quote("a", 3)
        };
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(moved.clone())], 2).expect("move");
        assert_eq!(
            load(&conn, DEFAULT_BOARD_ID).expect("load").items,
            vec![moved]
        );
    }

    #[test]
    fn delete_removes_the_item() {
        let mut conn = open_in_memory();
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("a", 0))], 1).expect("add");
        apply_ops(
            &mut conn,
            DEFAULT_BOARD_ID,
            &[BoardOp::Delete { id: "a".into() }],
            2,
        )
        .expect("delete");
        assert!(load(&conn, DEFAULT_BOARD_ID)
            .expect("load")
            .items
            .is_empty());
    }

    #[test]
    fn a_failing_op_rolls_back_the_whole_batch() {
        let mut conn = open_in_memory();
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("keep", 0))], 1).expect("seed");

        let empty_quote = Item {
            content: ItemContent::Quote {
                text: "   ".into(),
                author: None,
            },
            ..quote("bad", 2)
        };
        let ops = [
            upsert(quote("new", 1)),
            BoardOp::Delete { id: "keep".into() },
            upsert(empty_quote),
        ];
        let err = apply_ops(&mut conn, DEFAULT_BOARD_ID, &ops, 2).expect_err("batch fails");
        assert!(matches!(err, BoardError::InvalidItem { .. }));

        let ids: Vec<_> = load(&conn, DEFAULT_BOARD_ID)
            .expect("load")
            .items
            .into_iter()
            .map(|i| i.id)
            .collect();
        assert_eq!(ids, ["keep"]);
    }

    #[test]
    fn rejects_image_with_unknown_media() {
        let mut conn = open_in_memory();
        let image = Item {
            content: ItemContent::Image {
                media_id: "missing".into(),
            },
            ..quote("i", 0)
        };
        let err = apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(image)], 1).expect_err("fails");
        assert!(matches!(err, BoardError::UnknownMedia { .. }));
    }

    #[test]
    fn rejects_invalid_geometry_and_text() {
        let cases = [
            Item {
                w: 0.0,
                ..quote("a", 0)
            },
            Item {
                x: f64::NAN,
                ..quote("a", 0)
            },
            Item {
                y: 1e9,
                ..quote("a", 0)
            },
            Item {
                rotation: 30.0,
                ..quote("a", 0)
            },
            Item {
                id: String::new(),
                ..quote("a", 0)
            },
            Item {
                content: ItemContent::Text {
                    text: "x".repeat(MAX_TEXT_LEN + 1),
                    variant: TextVariant::Note,
                },
                ..quote("a", 0)
            },
        ];
        for item in cases {
            let mut conn = open_in_memory();
            let result = apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(item.clone())], 1);
            assert!(
                matches!(result, Err(BoardError::InvalidItem { .. })),
                "{item:?} should be rejected"
            );
        }
    }

    #[test]
    fn unknown_board_is_an_error() {
        let mut conn = open_in_memory();
        assert!(matches!(
            load(&conn, "nope"),
            Err(BoardError::UnknownBoard(_))
        ));
        assert!(matches!(
            apply_ops(&mut conn, "nope", &[upsert(quote("a", 0))], 1),
            Err(BoardError::UnknownBoard(_))
        ));
    }

    #[test]
    fn item_ids_cannot_be_taken_over_by_another_board() {
        let mut conn = open_in_memory();
        conn.execute(
            "INSERT INTO boards (id, name, created_at, updated_at) VALUES ('other', '', 0, 0)",
            [],
        )
        .expect("second board");
        apply_ops(&mut conn, DEFAULT_BOARD_ID, &[upsert(quote("a", 0))], 1).expect("add");
        let result = apply_ops(&mut conn, "other", &[upsert(quote("a", 5))], 2);
        assert!(matches!(result, Err(BoardError::InvalidItem { .. })));
        assert_eq!(load(&conn, DEFAULT_BOARD_ID).expect("load").items[0].z, 0);
    }

    #[test]
    fn serializes_items_in_the_shape_the_frontend_expects() {
        let json = serde_json::to_value(quote("a", 0)).expect("serialize");
        assert_eq!(json["content"]["kind"], "quote");
        assert_eq!(json["content"]["author"], "Antoine de Saint-Exupéry");
        let op: BoardOp = serde_json::from_value(serde_json::json!({
            "op": "upsert",
            "item": {
                "id": "x", "x": 1.0, "y": 2.0, "w": 3.0, "h": 4.0, "rotation": 0.0, "z": 0,
                "content": { "kind": "image", "mediaId": "m1" }
            }
        }))
        .expect("deserialize");
        assert!(
            matches!(op, BoardOp::Upsert { item } if item.content == ItemContent::Image { media_id: "m1".into() })
        );
    }
}
