//! Daily tasks: small steps toward the vision, planned for today or tomorrow. Local only; the
//! stable ids and timestamps are there for a later sync with Almost-there.eu.

use chrono::NaiveDate;
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use specta::Type;

pub const MAX_TASK_LEN: usize = 200;
const MAX_ID_LEN: usize = 64;
const MAX_OPS_PER_BATCH: usize = 500;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Task {
    /// Generated by the frontend (UUID).
    pub id: String,
    /// The day the task is planned for, `YYYY-MM-DD` (local date).
    pub day: String,
    pub text: String,
    pub done: bool,
    /// Order within the day; lower comes first.
    pub position: i32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "op", rename_all = "camelCase")]
pub enum TaskOp {
    Upsert { task: Task },
    Delete { id: String },
}

#[derive(Debug, thiserror::Error)]
pub enum TaskError {
    #[error("task {id}: {reason}")]
    Invalid { id: String, reason: &'static str },
    #[error("too many operations in one batch")]
    TooManyOps,
    #[error(transparent)]
    Sqlite(#[from] rusqlite::Error),
}

pub fn is_day(value: &str) -> bool {
    value.len() == 10 && NaiveDate::parse_from_str(value, "%Y-%m-%d").is_ok()
}

fn validate(task: &Task) -> Result<(), TaskError> {
    let invalid = |reason| TaskError::Invalid {
        id: task.id.clone(),
        reason,
    };
    if task.id.is_empty() || task.id.len() > MAX_ID_LEN {
        return Err(invalid("id must be 1–64 characters"));
    }
    if !is_day(&task.day) {
        return Err(invalid("day must be YYYY-MM-DD"));
    }
    let text = task.text.trim();
    if text.is_empty() || text.chars().count() > MAX_TASK_LEN {
        return Err(invalid("text must be 1–200 characters"));
    }
    Ok(())
}

fn read(row: &rusqlite::Row<'_>) -> rusqlite::Result<Task> {
    Ok(Task {
        id: row.get(0)?,
        day: row.get(1)?,
        text: row.get(2)?,
        done: row.get(3)?,
        position: row.get(4)?,
    })
}

/// Tasks of the days `from..=to`, by day and position.
pub fn list(conn: &Connection, from: &str, to: &str) -> Result<Vec<Task>, TaskError> {
    let mut stmt = conn.prepare(
        "SELECT id, day, text, done, position FROM tasks
         WHERE day BETWEEN ?1 AND ?2 ORDER BY day, position, created_at",
    )?;
    let rows = stmt.query_map(params![from, to], read)?;
    Ok(rows.collect::<Result<_, _>>()?)
}

/// Tasks left undone on days before `day`, to be moved to it or dropped.
pub fn unfinished_before(conn: &Connection, day: &str) -> Result<Vec<Task>, TaskError> {
    let mut stmt = conn.prepare(
        "SELECT id, day, text, done, position FROM tasks
         WHERE day < ?1 AND done = 0 ORDER BY day, position, created_at",
    )?;
    let rows = stmt.query_map(params![day], read)?;
    Ok(rows.collect::<Result<_, _>>()?)
}

/// Applies a batch of edits atomically: all or nothing.
pub fn apply(conn: &mut Connection, ops: &[TaskOp], now_ms: i64) -> Result<(), TaskError> {
    if ops.len() > MAX_OPS_PER_BATCH {
        return Err(TaskError::TooManyOps);
    }
    let tx = conn.transaction()?;
    for op in ops {
        match op {
            TaskOp::Upsert { task } => {
                validate(task)?;
                tx.execute(
                    "INSERT INTO tasks (id, day, text, done, position, created_at, updated_at)
                     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6)
                     ON CONFLICT (id) DO UPDATE SET day = excluded.day, text = excluded.text,
                        done = excluded.done, position = excluded.position,
                        updated_at = excluded.updated_at",
                    params![
                        task.id,
                        task.day,
                        task.text.trim(),
                        task.done,
                        task.position,
                        now_ms
                    ],
                )?;
            }
            TaskOp::Delete { id } => {
                tx.execute("DELETE FROM tasks WHERE id = ?1", [id])?;
            }
        }
    }
    tx.commit()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::db::open_in_memory;

    fn task(id: &str, day: &str, position: i32) -> Task {
        Task {
            id: id.into(),
            day: day.into(),
            text: format!("Úkol {id}"),
            done: false,
            position,
        }
    }

    fn upsert(task: Task) -> TaskOp {
        TaskOp::Upsert { task }
    }

    #[test]
    fn evening_planning_keeps_the_order_of_adding() {
        let mut conn = open_in_memory();
        let tomorrow = "2026-10-11";
        let ops = [
            upsert(task("a", tomorrow, 0)),
            upsert(task("b", tomorrow, 1)),
            upsert(task("c", tomorrow, 2)),
        ];
        apply(&mut conn, &ops, 1).expect("apply");
        let ids: Vec<_> = list(&conn, tomorrow, tomorrow)
            .expect("list")
            .into_iter()
            .map(|t| t.id)
            .collect();
        assert_eq!(ids, ["a", "b", "c"]);
    }

    #[test]
    fn updates_and_deletes() {
        let mut conn = open_in_memory();
        apply(&mut conn, &[upsert(task("a", "2026-10-10", 0))], 1).expect("add");
        let mut done = task("a", "2026-10-10", 0);
        done.done = true;
        done.text = "  Hotovo  ".into();
        apply(&mut conn, &[upsert(done)], 2).expect("update");
        let stored = list(&conn, "2026-10-10", "2026-10-10").expect("list");
        assert!(stored[0].done);
        assert_eq!(stored[0].text, "Hotovo");

        apply(&mut conn, &[TaskOp::Delete { id: "a".into() }], 3).expect("delete");
        assert!(list(&conn, "2026-10-10", "2026-10-10")
            .expect("list")
            .is_empty());
    }

    #[test]
    fn finds_unfinished_tasks_of_past_days() {
        let mut conn = open_in_memory();
        let mut done = task("done", "2026-10-09", 0);
        done.done = true;
        let ops = [
            upsert(task("old", "2026-10-08", 0)),
            upsert(task("yesterday", "2026-10-09", 1)),
            upsert(done),
            upsert(task("today", "2026-10-10", 0)),
        ];
        apply(&mut conn, &ops, 1).expect("apply");
        let ids: Vec<_> = unfinished_before(&conn, "2026-10-10")
            .expect("unfinished")
            .into_iter()
            .map(|t| t.id)
            .collect();
        assert_eq!(ids, ["old", "yesterday"]);
    }

    #[test]
    fn rejects_bad_tasks_and_keeps_the_batch_atomic() {
        let mut conn = open_in_memory();
        let mut long = task("long", "2026-10-10", 0);
        long.text = "x".repeat(MAX_TASK_LEN + 1);
        let mut empty = task("empty", "2026-10-10", 0);
        empty.text = "   ".into();
        for bad in [
            long,
            empty,
            task("day", "10.10.2026", 0),
            task("", "2026-10-10", 0),
        ] {
            assert!(apply(
                &mut conn,
                &[upsert(task("ok", "2026-10-10", 0)), upsert(bad)],
                1
            )
            .is_err());
        }
        assert!(list(&conn, "2000-01-01", "2100-01-01")
            .expect("list")
            .is_empty());
    }
}
